### ISSUE TITLE
[Todo] Input field and list of todos

### ISSUE THREAD

**Issue by mule-heo** [mule-heo/todo#2]
- [x] add text type input field
- [x] add submit button
  - [x] add event listener
- [x] add list of todos
  - [x] show todo text
  - [x] add delete button
  - [x] add event listener
  - [ ] ~~install uuid~~  (improper)
